### PR TITLE
新增LUV/ZPM/UV电动泵配方

### PR DESCRIPTION
**Pull request by Flyingcucumber**
新增LUV/ZPM/UV电动泵配方
【丁苯橡胶环】现在可以代替【硅胶环】参与合成

### CODE REVIEW

**Comment by Dabai1025** [comment]
@Flyingcucumber  are you passed ur code when u restarted game?

**Comment by Dabai1025** [comment]
it seems ok

**Review by Dabai1025 — APPROVED** [review]

**Comment by Flyingcucumber** [comment]
@Dabai1025 看我亲爱的截图，三个配方都能用
look at my lovely screensock, it runs fine.

**Pull request merged**
